- hosts: '{{ host }}'
  remote_user: root
  gather_facts: no
  serial: 1
  vars_files:
    - ../conf/default/services.yml
    - ../conf/{{ folder }}_k8s/resources.yml
    - ../conf/{{ folder }}_k8s/services.yml
    - ./{{ folder }}/global.yml
    - ./{{ folder }}/services.yml
  tasks: 
    - name: prepare configs
      set_fact:
        service_configs: "{{service_configs | combine(service_additional_configs, recursive=True)}}" 
        deploy_conf: "{{deploy_configs[service_name]}}"
    - name: prepare server_port
      set_fact:
        server_port: "{{service_configs[service_name].server_port}}"
    - name: deploy normal service
      include_tasks: ./deploy_stateless.yml
      when:
        - not (service_name is search("reactflow2"))
        - service_name != 'hadoopods'
    - name: deploy reactflow service
      include_tasks: ./deploy_reactflow.yml
      when: service_name is search("reactflow2")
    - name: deploy hadoopods service
      include_tasks: ./deploy_hadoopods.yml
      when: service_name == 'hadoopods' 

 

