- hosts: 127.0.0.1
  connection: local  
  remote_user: root
  gather_facts: no
  serial: 1
  vars_files:
    - ./{{ folder }}/services.yml
  tasks: 
    - name: prepare configs
      set_fact:
        service_configs: "{{service_configs | combine(service_additional_configs, recursive=True)}}" 
        deploy_conf: "{{deploy_configs[service_name]}}"
    - name: prepare server_port
      set_fact:
        server_port: "{{deploy_configs[service_name].server_port}}"
    - name: deploy normal service
      include_tasks: ./deploy_stateless.yml