- hosts: '{{ host }}'
  remote_user: root
  gather_facts: no
  serial: 1
  tasks: 
    - name: scale {{ service_name }} to {{ replicas }} replicas
      shell: kubectl scale deployment {{ service_name }} --replicas={{ replicas }} --namespace {{ namespace }}
    - name: check deployment result
      shell: kubectl rollout status deployment {{ service_name }} --namespace {{ namespace }}
      register: query_status
      until: query_status.stdout.find("successfully rolled out") != -1
      retries: 10
      delay: 15

 

