- hosts: '{{ hosts }}'
  gather_facts: no
  serial: 1
  vars_files:
    - ../conf/{{folder}}/resources.yml
    - ../conf/default/services.yml
    - ../conf/{{folder}}/services.yml
    - ./{{folder}}/global.yml
    - ./{{folder}}/services.yml
  tasks: 
    - name: prepare configs
      set_fact:
        service_configs: "{{service_configs | combine(service_additional_configs, recursive=True)}}" 
        deploy_conf: "{{deploy_configs[service_name]}}"
    - name: prepare server_port
      set_fact:
        server_port: "{{service_configs[service_name].server_port}}"
    - name: prepare published_ports in "18009:18009" pattern
      set_fact:
        published_ports: "{{(published_ports | default([])) + [item|string + ':' + item|string] }}"
      with_items: "{{exposed_ports}}"
      vars:
        exposed_ports: "{{[server_port] + (deploy_conf.published_ports | default([]))}}"
    - name: deploy service
      include_tasks: ./docker.yml

 

