apiVersion: apps/v1
kind: Deployment
metadata:
  name: "NAME"
  namespace: "SPACE"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "NAME"
  template:
    metadata:
      labels:
        app: "NAME"
    spec:
      imagePullSecrets:
      - name: xsio-registry-secret
      volumes:
      - name: log-volume
        hostPath:
          path: /opt/log/stash
          type: DirectoryOrCreate
      - name: tmp-volume
        hostPath:
          path: /opt/tmp
          type: DirectoryOrCreate
      containers:
      - name: "NAME"
        image: "nexus.cd.xsio.cn/DOCKERIMAGE:TAG"
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: PORT
        env:
        envFrom:
        - configMapRef:
            name: global-config
        - configMapRef:
            name: NAME-config
        volumeMounts:
        - mountPath: /opt/log/stash
          name: log-volume
        - mountPath: /var/tmp
          name: tmp-volume
        - mountPath: /tmp
          name: tmp-volume
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "2048Mi"
            cpu: "1000m"

        readinessProbe:
          httpGet:
            path: /ping
            port: web
          initialDelaySeconds: 60
          periodSeconds: 30
        livenessProbe:
          tcpSocket:
            port: web
          initialDelaySeconds: 60
          periodSeconds: 30

---
apiVersion: v1
kind: Service
metadata:
  name: "NAME"
  namespace: "SPACE"
spec:
  ports:
  - name: web
    port: PORT
    protocol: TCP
    targetPort: web
  selector:
    app: NAME
  sessionAffinity: None
  type: ClusterIP
---
