- hosts: '{{ host }}'
  remote_user: uowdev
  gather_facts: no
  serial: 1
  environment:
    http_proxy: ""
    https_proxy: ""
  tasks: 
    - name: deploy normal service
      include_tasks: ./deploy_stateless.yml
      when:
        - not (service_name is search("reactflow2"))
        - service_name != 'hadoopods'
    - name: deploy reactflow service
      include_tasks: ./deploy_reactflow.yml
      when: service_name is search("reactflow2")
    - name: deploy hadoopods service
      include_tasks: ./deploy_hadoopods.yml
      when: service_name == 'hadoopods' 

 

