- hosts: '127.0.0.1'
  connection: local
  gather_facts: no
  vars_files:
    - ../conf/{{folder}}/resources.yml
    - ../conf/default/services.yml
    - ../conf/{{folder}}/services.yml
  tasks:  
    - name: merge services
      set_fact:
        service_configs: "{{service_configs | combine(service_additional_configs, recursive=True)}}"  
    - name: dump
      debug:
        msg: '{{service_configs}}'
    # - name: set service internal urls
    #   debug: 
    #     msg: "http://{{item.key}}.service.consul:{{item.value['server_port']}}"
    #   with_dict: "{{service_configs}}"
    #   when: ('server_port' in item.value)