- hosts: '{{ host }}'
  gather_facts: no
  vars_files:
    - ../conf/{{folder}}/resources.yml
    - ../conf/default/services.yml
    - ../conf/{{folder}}/services.yml
    - ../conf/{{folder}}/endpoints.yml
  tasks:  
    - name: merge service configs
      set_fact:
        service_configs: "{{service_configs | combine(service_additional_configs, recursive=True)}}" 
    - name: set global resources variables
      uri: 
        url: 'http://127.0.0.1:8500/v1/kv/convertlab/global/{{ item.key }}'
        method: PUT
        body: !!str "{{ item.value }}"
      with_dict: '{{global}}'
    - name: set public urls
      uri:
        url: 'http://127.0.0.1:8500/v1/kv/convertlab/global/{{ item.key }}'
        method: PUT
        body: "{{item.value}}"
      with_dict: '{{endpoints.public}}'
    - name: set service internal urls
      uri: 
        url: 'http://127.0.0.1:8500/v1/kv/convertlab/global/{{item.key}}_internal_url'
        method: PUT
        body: "http://{{item.key}}.service.consul:{{item.value['server_port']}}"
      with_dict: "{{service_configs}}"
      when: ('server_port' in item.value)
    - name: set internal urls
      uri:
        url: 'http://127.0.0.1:8500/v1/kv/convertlab/global/{{ item.key }}'
        method: PUT
        body: "{{item.value}}"
      with_dict: '{{endpoints.internal}}'
    - name: set service env variables
      include_tasks: ./set_service_env.yml
      vars:
        service_name: '{{conf.key}}'
        service_vars: '{{conf.value}}'
      with_dict: '{{service_configs}}'
      loop_control:
        loop_var: conf