---
# archive docker images from remote nexus to local directory
# huangchun@20181129

- import_playbook: start_docker_registry.yml

- name: archive docker images
  hosts: 127.0.0.1
  connection: local
  become: yes
  vars_files:
    - "../conf/{{ landscape }}/resources.yml"
    - "../conf/default/services.yml"
    - "../conf/{{ landscape }}/services.yml"
    - "./{{ landscape }}/global.yml"
    - "./{{ landscape }}/services.yml"
  tasks:
    - name: load application images
      docker_image:
        name: "{{ docker_registry_addr }}/{{ landscape }}/{{ deploy_configs[item]['image_name'] }}:{{ deploy_configs[item]['image_tag'] | default(unified_image_tag) }}"
        repository: "127.0.0.1:5000/{{ landscape }}/{{ deploy_configs[item]['image_name'] }}:{{ deploy_configs[item]['image_tag'] | default(unified_image_tag) }}"
      loop: "{{ deploy_configs.keys() | list }}"

    - name: push application images to local
      docker_image:
        name: "127.0.0.1:5000/{{ landscape }}/{{ deploy_configs[item]['image_name'] }}:{{ deploy_configs[item]['image_tag'] | default(unified_image_tag) }}"
        push: yes
      loop: "{{ deploy_configs.keys() | list }}"
      register: push_result

    - debug:
        msg: "successfully archived {{ deploy_configs.keys() | list | length }} images to {{ playbook_dir }}/registry/"