deploy_configs:
  ads:
    image_name: ads
    replicas: 1

  su2-ads:
    image_name: ads
    replicas: 1

  adseventsloader2:
    image_name: adseventsloader2
    replicas: 1

  su2-adseventsloader2:
    image_name: adseventsloader2
    replicas: 1

  alipay:
    image_name: alipay
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  api:
    image_name: api
    replicas: 4
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  app:
    image_name: app
    replicas: 2
    liveness_initial_delay: 120
    liveness_period: 30
    readiness_initial_delay: 90
    readiness_period: 30
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  appui:
    image_name: appui
    replicas: 2
    no_health_check: true
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  canary-appui:
    image_name: appui
    replicas: 1
    no_health_check: true

  cms:
    image_name: cms
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  collectorentry:
    image_name: collectorentry
    replicas: 4
    extra_ports:
    - 18008
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  customer:
    image_name: customer
    replicas: 4
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  customerbackend:
    image_name: customer
    replicas: 4
    requests_cpu: 4000m
    limits_cpu: 4000m
    requests_memory: 9216Mi
    limits_memory: 9216Mi

  datapermission:
    image_name: datapermission
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  oauth2:
    image_name: oauth2
    replicas: 1

  su2-customer:
    image_name: customer
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  su3-customer:
    image_name: customer
    replicas: 3
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  su2-customerbackend:
    image_name: customer
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  su3-customerbackend:
    image_name: customer
    replicas: 3
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 8192Mi

  etlv2:
    image_name: etlv2
    replicas: 3
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 4096Mi
    limits_memory: 8192Mi

  eventjob:
    image_name: eventjob
    replicas: 3
    requests_cpu: 2000m
    requests_memory: 4096Mi
    limits_cpu: 3000m
    limits_memory: 8192Mi

  extensionplatform:
    image_name: extensionplatform
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  file:
    image_name: file
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  flowmanager:
    image_name: flowmanager
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  goods:
    image_name: goods
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  hosting:
    image_name: hosting
    replicas: 4
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  canary-hosting:
    image_name: hosting
    replicas: 1

  job:
    image_name: job
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 4096Mi

  kanglai:
    image_name: kanglai
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 4096Mi

  loyaltyv2:
    image_name: loyaltyv2
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi
  
   su2-loyaltyv2:
    image_name: loyaltyv2
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi


  maxwell:
    image_name: maxwell
    replicas: 1
    disableRolling: true
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 4096Mi
    limits_memory: 8192Mi

  su2-maxwell:
    image_name: maxwell
    replicas: 1
    disableRolling: true
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 4096Mi
    limits_memory: 8192Mi

  su3-maxwell:
    image_name: maxwell
    replicas: 1
    disableRolling: true
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 4096Mi
    limits_memory: 8192Mi

  plugin:
    image_name: plugin
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  reactflow2:
    image_name: reactflow2
    replicas: 1
    requests_memory: 6144Mi
    limits_memory: 12288Mi
    requests_cpu: 6000m
    limits_cpu: 6000m


  su3-reactflow2:
    image_name: reactflow2
    replicas: 1
    requests_memory: 6144Mi
    limits_memory: 10240Mi
    requests_cpu: 1000m
    extra_ports:
    - 8558
    - 2551

  scheduler:
    image_name: scheduler
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 4096Mi

  sms:
    image_name: sms
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 8000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  urlshortener:
    image_name: urlshortener
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 8000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  webhook:
    image_name: webhook
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 8000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  wechat:
    image_name: wechat
    replicas: 6
    requests_cpu: 4000m
    limits_cpu: 4000m
    requests_memory: 2048Mi
    limits_memory: 10240Mi

  wechatjob:
    image_name: wechat
    replicas: 4
    requests_cpu: 1000m
    limits_cpu: 8000m
    requests_memory: 4096Mi
    limits_memory: 10240Mi

  wechatcorp:
    image_name: wechatcorp
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  wechatpay:
    image_name: wechatpay
    replicas: 3
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  wechatwork:
    image_name: wechatwork
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  wechatproxy:
    image_name: wechatproxy
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  referrer:
    image_name: referrer
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  tms:
    image_name: tms
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  mqmigration:
    image_name: mqmigration
    replicas: 1
    no_service: true

  appdbmigration:
    image_name: appdbmigration
    replicas: 1
    no_service: true

  su2-appdbmigration:
    image_name: appdbmigration
    replicas: 1
    no_service: true

  su3-appdbmigration:
    image_name: appdbmigration
    replicas: 1
    no_service: true

  customerdbmigration:
    image_name: customerdbmigration
    replicas: 1
    no_service: true

  cdhdbmigration:
    image_name: cdhdbmigration
    replicas: 1
    no_service: true

  su2-customerdbmigration:
    image_name: customerdbmigration
    replicas: 1
    no_service: true

  su3-customerdbmigration:
    image_name: customerdbmigration
    replicas: 1
    no_service: true

  loyaltydbmigration:
    image_name: loyaltydbmigration
    replicas: 1
    no_service: true

  su2-loyaltydbmigration:
    image_name: loyaltydbmigration
    replicas: 1
    no_service: true

  hadoopods:
    image_name: hadoopods
    replicas: 1
    liveness_initial_delay: 120
    liveness_period: 30
    readiness_initial_delay: 90
    readiness_period: 30
    requests_cpu: 2000m
    limits_cpu: 8000m
    requests_memory: 4096Mi
    limits_memory: 10240Mi

  hadoopdts:
    image_name: hadoopdts
    replicas: 3
    liveness_initial_delay: 120
    liveness_period: 30
    readiness_initial_delay: 90
    readiness_period: 30
    requests_cpu: 2000m
    limits_cpu: 4000m
    requests_memory: 4096Mi
    limits_memory: 10240Mi

  kafka2es:
    image_name: kafka2es
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi

  impala:
    image_name: impala
    replicas: 2
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 4096Mi
    limits_memory: 10240Mi

  datamining:
    image_name: datamining
    replicas: 1
    requests_cpu: 1000m
    limits_cpu: 4000m
    requests_memory: 1024Mi
    limits_memory: 8192Mi
