deploy_configs:
  kukaplatform:
    image_name: kukaplatform
    replicas: 1
    server_port: 18066
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  ruijie:
    image_name: ruijie
    replicas: 1
    server_port: 8208
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 3072Mi
  hublot:
    image_name: hublot
    replicas: 1
    server_port: 18069
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  rjmarketing:
    image_name: rjmarketing
    replicas: 1
    server_port: 8207
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  economicsui:
    image_name: economicsui
    replicas: 1
    server_port: 8028
    requests_cpu: 100m
    limits_cpu: 3000m
    requests_memory: 500Mi
    limits_memory: 4096Mi
  adminecmemberserverside:
    image_name: adminecmemberserverside
    replicas: 1
    server_port: 8080
  htmlecmemberserverside:
    image_name: htmlecmemberserverside
    replicas: 1
    server_port: 80
  appecmemberserverside:
    image_name: appecmemberserverside
    replicas: 1
    server_port: 8080
  devecmemberserverside:
    image_name: devecmemberserverside
    replicas: 1
    server_port: 80
  sam:
    image_name: sam
    replicas: 1
    server_port: 8102
    requests_cpu: 0
    limits_cpu: 3000m
    requests_memory: 500Mi
    limits_memory: 5120Mi
  diageojdorder:
    image_name: diageojdorder
    replicas: 1
    server_port: 8143
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  uowm2coupon:
    image_name: uowm2coupon
    replicas: 1
    server_port: 29036
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  youzanorderrt:
    image_name: youzanorderrt
    replicas: 1
    server_port: 8902
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  qimenordertmallorderplugin:
    image_name: qimenordertmallorderplugin
    replicas: 1
    server_port: 8109
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  kukahomescrmadminplugin:
    image_name: kukahomescrmadminplugin
    replicas: 1
    server_port: 8070
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  kukahomekukahomeadmin:
    image_name: kukahomekukahomeadmin
    replicas: 1
    server_port: 8100
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  demoautocustomer:
    image_name: demoautocustomer
    replicas: 1
    server_port: 8012
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  kukahomescrmweb:
    image_name: kukahomescrmweb
    replicas: 1
    server_port: 8050
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  kukahomescrminteraction:
    image_name: kukahomescrminteraction
    replicas: 1
    server_port: 8008
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
  cfb:
    image_name: cfb-cfb
    replicas: 1
    server_port: 18123
    requests_cpu: 0
    limits_cpu: 2000m
    requests_memory: 500Mi
    limits_memory: 2048Mi
