deploy_configs:
  kukaplatform:
    image_name: kukaplatform
    replicas: 1
    server_port: 18066
    requests_cpu: 100m
    limits_cpu: 3000m
    requests_memory: 1500Mi
    limits_memory: 4096Mi
  ruijie:
    image_name: ruijie
    replicas: 1
    server_port: 8208
    requests_cpu: 100mi
    limits_cpu: 3000m
    requests_memory: 1500Mi
    limits_memory: 4096Mi

