apiVersion: v1
kind: Endpoints
metadata:
  name: elasticsearch
  namespace: test
subsets:
  - addresses:
    - ip: 192.168.2.2
    ports:
    - name: p1
      port: 9200
    - name: p2
      port: 9300

---

apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: test
spec:
  ports:
  - name: p1
    port: 9200
    targetPort: 9200
  - name: p2
    port: 9300
    targetPort: 9300