apiVersion: v1
kind: Endpoints
metadata:
  name: kafka
  namespace: test
subsets:
  - addresses:
    - ip: 10.0.3.80
    ports:
    - port: 9092

---

apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: test
spec:
  ports:
  - port: 9092
    targetPort: 9092