apiVersion: v1
kind: Endpoints
metadata:
  name: rabbitmq
  namespace: test
subsets:
  - addresses:
    - ip: 10.0.3.80
    ports:
    - port: 5672

---

apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: test
spec:
  ports:
  - port: 5672
    targetPort: 5672