apiVersion: v1
kind: Endpoints
metadata:
  name: zookeeper
  namespace: test
subsets:
  - addresses:
    - ip: 10.0.2.120
    ports:
    - port: 2181

---

apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: test
spec:
  ports:
  - port: 2181
    targetPort: 2181