---
- name: generate {{service_name}} configmap yaml
  template:
    src: ./configmap.j2
    dest: /tmp/{{ namespace }}-{{service_name}}.yaml
- name: create or update {{service_name}} configmap
  k8s:
    force: True
    state: present
    src: /tmp/{{ namespace }}-{{service_name}}.yaml
  register: execute_result
- debug:
    msg: "execute result: {{ execute_result }}"
- name: remove {{service_name}} yaml
  file:
    path: /tmp/{{ namespace }}-{{service_name}}.yaml
    state: absent