deploy_configs:
  ads:
    image_name: ads
    hosts:
      - p09

  adseventsloader2:
    image_name: adseventsloader2
    hosts:
      - p07

  api:
    image_name: api
    hosts:
      - p05
      - p0501

  app:
    image_name: app
    hosts:
      - p0601
      - p07
      - p10
      - p11
      - p12

  appdbmigration:
    image_name: appdbmigration
    hosts:
      - p06

  appui:
    image_name: appui
    hosts:
      - p01
      - p04

  cdhdbmigration:
    image_name: cdhdbmigration
    hosts:
      - p03
  
  cms:
    image_name: cms
    hosts:
      - p02

  collectorentry:
    image_name: collectorentry
    published_ports: [18008]
    hosts:
      - p05
      - p07

  customer:
    image_name: customer # "nexus.xiso.cn/<env>/${image_name}:${tag}"
    hosts:
      - p0601
      - p06
      - p07
      - p05

  customerbackend:
    image_name: customer
    hosts:
      - p01
      - p02
      - p08
      - p12
  
  customerdbmigration:
    image_name: customerdbmigration
    hosts:
      - p06
        
  datamining:
    image_name: datamining
    hosts:
      - p02

  dts:
    image_name: dts
    hosts:
      - p03

  etlv2:
    image_name: etlv2
    hosts:
      - p10
      - p11

  eventjob:
    image_name: eventjob
    hosts:
      - p05
      - p11
      - p12

  file:
    image_name: file
    hosts:
      - p06

  flowmanager:
    image_name: flowmanager
    hosts:
      - p0601

  goods:
    image_name: goods
    hosts:
      - p03

  hadoopdts:
    image_name: hadoopdts
    hosts:
      - p0601

  hosting:
    image_name: hosting
    hosts:
      - p10
      - p11

  impala:
    image_name: impala
    hosts:
      - p01

  job:
    image_name: job
    hosts:
      - p03

  kafka2es:
    image_name: kafka2es
    hosts:
      - p03

  kanglai:
    image_name: kanglai
    hosts:
      - p0501
      - p05

  loyaltyv2:
    image_name: loyaltyv2
    hosts:
      - p02
      - p03

  loyaltydbmigration:
    image_name: loyaltydbmigration
    hosts:
      - p02

  maxwell:
    image_name: maxwell
    hosts:
      - p08

  mqmigration:
    image_name: mqmigration
    hosts:
      - p05

  plugin:
    image_name: plugin
    hosts:
      - p10
      - p11

  reactflow2:
    image_name: reactflow2
    hosts:
      - p09

  referrer:
    image_name: referrer
    hosts:
      - p11

  scheduler:
    image_name: scheduler
    hosts:
      - p03

  sms:
    image_name: sms
    hosts:
      - p02
      - p10

  tms:
    image_name: tms
    hosts:
      - p08

  urlshortener:
    image_name: urlshortener
    hosts:
      - p09

  webhook:
    image_name: webhook
    hosts:
      - p07

  wechat:
    image_name: wechat
    hosts:
      - p04
      - p08
      - p10
      - p11
      - p06
      - p07
      - p09
      - p12

  wechatcorp:
    image_name: wechatcorp
    hosts:
      - p08

  wechatpay:
    image_name: wechatpay
    hosts:
      - p06

  wechatproxy:
    image_name: wechatproxy
    hosts:
      - p01

  wechatwork:
    image_name: wechatwork
    hosts:
      - p08

  


